set nu
set nocompatible
set backspace=indent,eol,start
set autoindent

set backspace=indent,eol,start

call pathogen#runtime_append_all_bundles()

" Switch syntax highlighting on
filetype off
filetype plugin indent off

set runtimepath+=$GOROOT/misc/vim
filetype plugin indent on
syntax on

color neverland2-darker

set nofoldenable " Say no to code folding...

set clipboard=unnamed

command! Q q " Bind :Q to :q
command! Qall qall 

" vim-latex
set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"

set tabstop=4     " tabs are at proper location
set noexpandtab     " don't use actual tab character (ctrl-v)
set shiftwidth=4  " indenting is 4 spaces
set autoindent    " turns it on
set smartindent   " does the right thing (mostly) in programs
set cindent       " stricter rules for C programs


" Disable Ex mode
map Q <Nop>

" golang
let g:gofmt_command = "goimports"
autocmd FileType go autocmd BufWritePre <buffer> Fmt

